{
  "host": "www.youtube.com",
  "port": 443,
  "protocol": "http",
  "isPublic": false,
  "status": "READY",
  "startTime": 1560205620262,
  "testTime": 1560206665961,
  "engineVersion": "1.35.1",
  "criteriaVersion": "2009p",
  "endpoints": [
    {
      "ipAddress": "216.58.195.238",
      "serverName": "sfo03s06-in-f14.1e100.net",
      "statusMessage": "Ready",
      "grade": "A+",
      "gradeTrustIgnored": "A+",
      "hasWarnings": false,
      "isExceptional": true,
      "progress": 100,
      "duration": 95060,
      "delegation": 2
    },
    {
      "ipAddress": "216.58.192.14",
      "serverName": "nuq04s29-in-f14.1e100.net",
      "statusMessage": "Ready",
      "grade": "A+",
      "gradeTrustIgnored": "A+",
      "hasWarnings": false,
      "isExceptional": true,
      "progress": 100,
      "duration": 95052,
      "delegation": 2
    },
    {
      "ipAddress": "216.58.194.174",
      "serverName": "sfo07s13-in-f174.1e100.net",
      "statusMessage": "Ready",
      "grade": "A+",
      "gradeTrustIgnored": "A+",
      "hasWarnings": false,
      "isExceptional": true,
      "progress": 100,
      "duration": 95004,
      "delegation": 2
    },
    {
      "ipAddress": "216.58.195.78",
      "serverName": "sfo07s16-in-f78.1e100.net",
      "statusMessage": "Ready",
      "grade": "A+",
      "gradeTrustIgnored": "A+",
      "hasWarnings": false,
      "isExceptional": true,
      "progress": 100,
      "duration": 95013,
      "delegation": 2
    },
    {
      "ipAddress": "216.58.194.206",
      "serverName": "sfo03s01-in-f14.1e100.net",
      "statusMessage": "Ready",
      "grade": "A+",
      "gradeTrustIgnored": "A+",
      "hasWarnings": false,
      "isExceptional": true,
      "progress": 100,
      "duration": 95073,
      "delegation": 2
    },
    {
      "ipAddress": "172.217.5.110",
      "serverName": "sfo03s07-in-f14.1e100.net",
      "statusMessage": "Ready",
      "grade": "A+",
      "gradeTrustIgnored": "A+",
      "hasWarnings": false,
      "isExceptional": true,
      "progress": 100,
      "duration": 94992,
      "delegation": 2
    },
    {
      "ipAddress": "172.217.6.46",
      "serverName": "sfo03s08-in-f14.1e100.net",
      "statusMessage": "Ready",
      "grade": "A+",
      "gradeTrustIgnored": "A+",
      "hasWarnings": false,
      "isExceptional": true,
      "progress": 100,
      "duration": 95006,
      "delegation": 2
    },
    {
      "ipAddress": "172.217.164.110",
      "serverName": "sfo03s18-in-f14.1e100.net",
      "statusMessage": "Ready",
      "grade": "A+",
      "gradeTrustIgnored": "A+",
      "hasWarnings": false,
      "isExceptional": true,
      "progress": 100,
      "duration": 95051,
      "delegation": 2
    },
    {
      "ipAddress": "172.217.6.78",
      "serverName": "sfo07s17-in-f78.1e100.net",
      "statusMessage": "Ready",
      "grade": "A+",
      "gradeTrustIgnored": "A+",
      "hasWarnings": false,
      "isExceptional": true,
      "progress": 100,
      "duration": 95048,
      "delegation": 2
    },
    {
      "ipAddress": "172.217.0.46",
      "serverName": "sfo07s26-in-f14.1e100.net",
      "statusMessage": "Ready",
      "grade": "A+",
      "gradeTrustIgnored": "A+",
      "hasWarnings": false,
      "isExceptional": true,
      "progress": 100,
      "duration": 95117,
      "delegation": 2
    },
    {
      "ipAddress": "2607:f8b0:4005:808:0:0:0:200e",
      "serverName": "sfo03s07-in-x0e.1e100.net",
      "statusMessage": "Ready",
      "grade": "A+",
      "gradeTrustIgnored": "A+",
      "hasWarnings": false,
      "isExceptional": true,
      "progress": 100,
      "duration": 95170,
      "delegation": 2
    }
  ]
}